version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
#   image: digi/app
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
    networks:
     - digi
#  ngrok:
#    image: wernight/ngrok
#    links:d
#      - app
#    ports:
#      - "4040:80"
#    volumes:
#      - .:/var/www/html
#    networks:
#      - digi
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - digimysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - digi
  redis:
    image: redis:alpine
    networks:
     - digi
networks:
  digi:
    driver: "bridge"
volumes:
  digimysql:
    driver: "local"
